spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.8.244:1521:bimtest
    username: bimtest1
    password: bimtest1
    driver-class-name: oracle.jdbc.OracleDriver
server:
  port: 8086

mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml